---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: ofss-ofss1
spec:
  replicas: 1
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - operator: DoesNotExist
                    key: node-role.kubernetes.io/master
      containers:
        - terminationMessagePath: /dev/termination-log
          name: ofss-ofss
          image: '168.130.1.31/daocloud/ofss:v1.0'
          terminationMessagePolicy: File
          env:
            - name: server_addr
              value: bbs.itaojin.me
            - name: hostname_in_docker
              value: rongzhitong-dev-k8s-32
            - name: ip_out_docker
              value: 168.130.1.32
            - name: ssh_port_out_docker
              value: '22'
            - name: TZ
              value: Asia/Chongqing
          imagePullPolicy: Always
          resources:
            requests:
              memory: '0'
            limits:
              cpu: '2'
              memory: '4294967296'