---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ofss-config-env
  namespace: kube-system
data:
  hostname_in_docker: daocloud-k8s-sh
  ip_out_docker: 10.25.10.20
  server_addr: bbs.itaojin.me
  ssh_port_out_docker: '22'
#下面是easyrsa生成证书所需要的变量,保持默认即可(下面变量已经写到容器启动脚本中,为了保证变量存在所以在这里也定义了一次)
  OPENVPN: /etc/openvpn
  EASYRSA_PKI: '/etc/openvpn/pki'
  EASYRSA_VARS_FILE: '/etc/openvpn/vars'
  EASYRSA: /usr/share/easy-rsa
  EASYRSA_CRL_DAYS: '3650'

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ofss-config-frpc
  namespace: kube-system
data:
  frpc-lite.ini: |-
    [common]
    server_addr = 0.0.0.0
    server_port = 7100
    log_file = console
    log_level = info
    log_max_days = 3
    privilege_token = 405520

    admin_addr = 127.0.0.1
    admin_port = 7400
    admin_user = admin
    admin_pwd = admin

    pool_count = 5
    tcp_mux = true
    #user = your_name
    login_fail_exit = true
    protocol = tcp

    [range:sshindocker hostname_in_docker]
    type = tcp
    local_ip = 127.0.0.1
    local_port = 22
    remote_port = 0
    use_encryption = true
    use_compression = true

    [range:sshoutdocker hostname_in_docker]
    type = tcp
    local_ip = ip_out_docker
    local_port = ssh_port_out_docker
    remote_port = 0
    use_encryption = false
    use_compression = false


    [range:openvpn hostname_in_docker]
    type = tcp
    local_ip = 127.0.0.1
    local_port = 1194
    remote_port = 0
    use_encryption = false
    use_compression = false

    [range:openvpn hostname_in_docker]
    type = udp
    local_ip = 127.0.0.1
    local_port = 1194
    remote_port = 0
    use_encryption = false
    use_compression = false

    [range:squid hostname_in_docker]
    type = tcp
    local_ip = 127.0.0.1
    local_port = 3128
    remote_port = 0
    use_encryption = false
    use_compression = false

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ofss
  namespace: kube-system
  labels:
    app: ofss
spec:
  selector:
    matchLabels:
      app: ofss
  template:
    metadata:
      name: ofss
      labels:
        app: ofss
    spec:
      containers:
        - name: ofss
          image: 'registry.cn-hangzhou.aliyuncs.com/sourcegarden/openvpn-fss:v0.3'
          envFrom:
            - configMapRef:
                name: ofss-config-env
          resources:
            limits:
              cpu: 500m
              memory: '500Mi'
            requests:
              cpu: '0'
              memory: '500Mi'
          volumeMounts:
            - name: ofss-config-frp-backup
              mountPath: /etc/frp-backup/
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: hostpath-time
              mountPath: /etc/localtime
            - name: hostpath-openvpn
              mountPath: /etc/openvpn
          imagePullPolicy: Always
          securityContext:
            privileged: true
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: ''
        - name: hostpath-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: hostpath-openvpn
          hostPath:
            path: /data/tools/ofss/openvpn
            type: ''
        - name: ofss-config-frp-backup
          configMap:
            name: ofss-config-frpc
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - dce-bj-node-13