apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  serviceName: mysql-master
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-master
        image: mysql57:master
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Iotmysql@12345"
        - name: MYSQL_REPLICATION_USER
          value: "repl"
        - name: MYSQL_REPLICATION_PASSWORD
          value: "abcd@1234"
        volumeMounts:
          - name: mysql-master-v
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysqlpvc
    spec:
      selector:
        matchLabels:
          name: pv01
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    name: pv01
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/
    server: 192.168.102.12
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  serviceName: mysql-slave
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-slave
        image: mysql57:slave
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Iotmysql@12345"
        - name: MYSQL_REPLICATION_USER
          value: "repl"
        - name: MYSQL_REPLICATION_PASSWORD
          value: "abcd@1234"
        volumeMounts:
          - name: mysql-slave-v
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysqlpvc
    spec:
      selector:
        matchLabels:
          name: pv02
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
  labels:
    name: pv02
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs01/
    server: 192.168.102.12
---
