version: "3"
services:
  n2n_edge_dhcpd:
    image: zctmdc/n2n_ntop:latest
    restart: always
    privileged: true
    environment:
      - MODE=DHCPD
      - SUPERNODE_PORT=10086
      - 2N_INTERFACE=edge0
      - STATIC_IP="10.0.10.1"
      - N2N_GROUP=zctmdc_proxy
      - N2N_PASS=zctmdc_proxy
      - N2N_SERVER=n2n.lucktu.com:10086
      - N2N_ARGS=-Av
    # volumes:
    #   - ./dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
  n2n_edge_dhcp:
    image: zctmdc/n2n_ntop:latest
    restart: always
    privileged: true
    environment:
      - MODE=DHCP
      - SUPERNODE_PORT=10086
      - 2N_INTERFACE=edge0
      - N2N_GROUP=zctmdc_proxy
      - N2N_PASS=zctmdc_proxy
      - N2N_SERVER=n2n.lucktu.com:10086
      - N2N_ARGS=-Avr
    command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
  n2n_edge_static:
    image: zctmdc/n2n_ntop:latest
    restart: always
    privileged: true
    environment:
      - MODE=STATIC
      - SUPERNODE_PORT=10086
      - 2N_INTERFACE=edge0
      - STATIC_IP="10.0.10.10"
      - N2N_GROUP=zctmdc_proxy
      - N2N_PASS=zctmdc_proxy
      - N2N_SERVER=n2n.lucktu.com:10086
      - N2N_ARGS=-Av
    command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
  n2n_supernode:
    image: zctmdc/n2n_ntop:latest
    restart: always
    privileged: true
    ports:
      - 10086:10086/udp
    environment:
      - MODE=SUPERNODE
      - SUPERNODE_PORT=10086
      - N2N_ARGS=-v
    command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]