version: "3"
services:
  n2n_edge_dhcpd:
    image: registry.cn-hangzhou.aliyuncs.com/sourcegarden/n2n:latest
    restart: always
    privileged: true
    environment:
      - MODE=DHCPD
      - SUPERNODE_PORT=10086
      - 2N_INTERFACE=edge0
      - STATIC_IP="10.0.10.1"
      - N2N_GROUP=funny_proxy
      - N2N_PASS=funny_proxy
      - N2N_SERVER=www.funny.com:10086
      - N2N_ARGS=-A2 -v
    # volumes:
    #   - ./dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
  n2n_edge_dhcp:
    image: registry.cn-hangzhou.aliyuncs.com/sourcegarden/n2n:latest
    restart: always
    privileged: true
    environment:
      - MODE=DHCP
      - SUPERNODE_PORT=10086
      - 2N_INTERFACE=edge0
      - N2N_GROUP=funny_proxy
      - N2N_PASS=funny_proxy
      - N2N_SERVER=www.funny.com:10086
      - N2N_ARGS=-A2 -vr
    command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
  n2n_edge_static:
    image: registry.cn-hangzhou.aliyuncs.com/sourcegarden/n2n:latest
    restart: always
    privileged: true
    environment:
      - MODE=STATIC
      - SUPERNODE_PORT=10086
      - 2N_INTERFACE=edge0
      - STATIC_IP="10.0.10.10"
      - N2N_GROUP=funny_proxy
      - N2N_PASS=funny_proxy
      - N2N_SERVER=www.funny.com:10086
      - N2N_ARGS=-A2 -v
    command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
  n2n_supernode:
    image: registry.cn-hangzhou.aliyuncs.com/sourcegarden/n2n:latest
    restart: always
    privileged: true
    ports:
      - 10086:10086/udp
    environment:
      - MODE=SUPERNODE
      - SUPERNODE_PORT=10086
      - N2N_ARGS=-v
    command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
