version: "3"
services:
    n2n_proxy_nat:
      image: zctmdc/n2n_proxy:latest
      restart: always
      privileged: true
      environment:
        - MODE=DHCPD
        - STATIC_IP=10.0.10.1
        - N2N_GROUP=zctmdc_proxy
        - N2N_PASS=zctmdc_proxy
        - N2N_SERVER=n2n.lucktu.com:10086
        - N2N_NAT=TRUE
        - N2N_ARGS=-Av
        - N2N_PROXY=TRUE
      volumes:
        - ./dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]

    n2n_proxy_gw_dhcp:
      image: zctmdc/n2n_proxy:latest
      restart: always
      privileged: true
      environment:
        - MODE=DHCP
        - N2N_GROUP=zctmdc_proxy
        - N2N_PASS=zctmdc_proxy
        - N2N_SERVER=n2n.lucktu.com:10086
        - N2N_GW=TURE
        - N2N_DESTINATION=192.168.0.0/16
        - N2N_GATEWAY=10.0.10.1
        - N2N_ARGS=-Avr
        - N2N_PROXY=TRUE
      volumes:
        - ../n2n_ntop/edge-dhcp-server/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      ports:
        - 1080:1080
      command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]

    n2n_proxy_gw_static:
      image: zctmdc/n2n_proxy:latest
      restart: always
      privileged: true
      environment:
        - MODE=STATIC
        - STATIC_IP=10.0.10.20
        - N2N_GROUP=zctmdc_proxy
        - N2N_PASS=zctmdc_proxy
        - N2N_SERVER=n2n.lucktu.com:10086
        - N2N_GW=TURE
        - N2N_DESTINATION=192.168.0.0/16
        - N2N_GATEWAY=10.0.10.1
        - N2N_ARGS=-Av
        - N2N_PROXY=FALSE
      # volumes:
      #   - n2n_proxy_nat/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      ports:
        - 10080:1080
      command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
