FROM docker:latest

ARG ssh_pub_key
ARG ssh_pri_key

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

RUN mkdir -p /root/.ssh \
    && chmod 0700 /root/.ssh \
    && echo "$ssh_pub_key" > /root/.ssh/authorized_keys \
    && echo "$ssh_pri_key" > /root/.ssh/id_rsa \
    && echo "$ssh_pub_key" > /root/.ssh/id_rsa.pub \
    && chmod 600 /root/.ssh/id_rsa \
    && chmod 644 /root/.ssh/id_rsa.pub \
    && apk add bash nano tmux openrc openssh htop\
    && echo -e "PasswordAuthentication no" >> /etc/ssh/sshd_config \
    && sed -i "s/#PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config \
#    && ssh-keygen -A \
    && ssh-keygen -t dsa -P "" -f /etc/ssh/ssh_host_dsa_key \
    && ssh-keygen -t rsa -P "" -f /etc/ssh/ssh_host_rsa_key \ 
    && ssh-keygen -t ecdsa -P "" -f /etc/ssh/ssh_host_ecdsa_key \
    && ssh-keygen -t ed25519 -P "" -f /etc/ssh/ssh_host_ed25519_key \
    && echo "root:abc123456" | chpasswd \
    && mkdir -p /run/openrc \
    && touch /run/openrc/softlevel

COPY ./prod-transfer.sh /usr/local/bin/
COPY ./busybox /usr/local/bin/
COPY ./config.json /root/.docker/
RUN chmod +x /usr/local/bin/prod-transfer.sh && chmod +x /usr/local/bin/busybox

#ENTRYPOINT ["sh", "-c", "rc-status; rc-service sshd start"]
#CMD ["sh", "-c", "rc-status; rc-service sshd start"]
CMD ["/usr/sbin/sshd", "-D"]
