version: "3"
services:
  postal:
    image: registry.cn-hangzhou.aliyuncs.com/sourcegarden/postal:alpine
    #build: .
    container_name: postal
    command: run
    ports:
      - 127.0.0.1:25:25
    depends_on:
      - "mysql"
      - "rabbitmq"
    volumes:
      - /data/postal/storage:/storage
      - /data/postal/public:/opt/postal/public
      - /data/postal/assets:/opt/postal/public/assets
      - ./src/templates/:/templates
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=postal
      - POSTAL_FNAME=Sia
      - POSTAL_LNAME=Cat
      - POSTAL_PASSWORD=changeme
      - POSTAL_EMAIL=cyrus@tranc.io
    healthcheck:
      test: curl -sS http://127.0.0.1:5000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
  mysql:
    image: mariadb:10
    container_name: postal_mysql
    ports:
      - 3306:3306
    volumes:
      - /data/postal/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: postal_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=/postal
  nginx:
    image: nginx
    container_name: postal_nginx
    ports:
      - 80:80
    links:
      - postal
    depends_on:
      - postal
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /data/postal/public:/opt/postal/public:ro
      - /data/postal/assets:/opt/postal/public/assets:ro
