FROM docker:20-dind
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV AWS_DEFAULT_REGION ${AWS_DEFAULT_REGION}
ENV AWS_REGION ${AWS_REGION}
ENV DOCKER_HOST tcp://docker:2375
ENV DOCKER_DRIVER overlay2
ENV VERSION v1
ENV EKS_CLUSTER_PREFIX "PositecEksDev"
ENV ECR_STR "680218613974.dkr.ecr.us-east-1.amazonaws.com"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add aws-cli gettext curl busybox-extras bash --no-cache \
    && wget https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl 
RUN sh -c 'curl  --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp' \
    && chmod +x kubectl \
    && chmod +x /tmp/eksctl \
    && mv kubectl /tmp/eksctl /usr/local/bin/



CMD ["sh"]
