apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
  namespace: redis-ns
  labels:
    app: redis-cluster-service
spec:
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis-cluster
