apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: xxl-job-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job-admin
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
      - name: xxl-job-admin
        image: xuxueli/xxl-job-admin:2.3.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PARAMS
          value: "--spring.datasource.url=jdbc:mysql://10.4.19.70:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&useSSL=false --spring.datasource.username=xxljob --spring.datasource.password=xxljob123 --spring.mail.username=wei.pan@thundersoft.com --spring.mail.password=Goaway"
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: xxl-job-admin
  labels:
    app: xxl-job-admin
spec:
  ports:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    #protocol: TCP
    #name: http
  selector:
    app: xxl-job-admin
