apiVersion: v1
kind: Namespace
metadata:
  name: redis-ns
  labels:
    name: redis-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis-ns
type: Opaque
data:
  redisAuthPass: cmVkaXNwYXNz 
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis-ns
  labels:
    name: redis-master
spec:
  ports:
    - port: 6379
  selector:
    redis-master: "true"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: redis-ns
  labels:
    name: redis-master
spec:
  serviceName: redis-master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        redis-master: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: 10.100.10.130/daocloud/redis:v3.2.11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: MASTER
          value: "true"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redisAuthPass
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-master-volume
          mountPath: /redis-master-data
  volumeClaimTemplates:
  - metadata:
      name: redis-master-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
